# Generated by Django 4.0.3 on 2022-03-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enreg',
            name='field1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enreg',
            name='field2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
