# Generated by Django 4.0.3 on 2022-03-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_enreg_field1_alter_enreg_field2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='nb_max_enregs',
        ),
        migrations.AddField(
            model_name='file',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
