# Generated by Django 4.0.3 on 2022-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enreg',
            name='block',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Enreg',
        ),
    ]
