# Generated by Django 4.0.3 on 2022-03-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_nb_max_enregs_file_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='data',
        ),
        migrations.AddField(
            model_name='file',
            name='nb_max_enregs',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
