# Generated by Django 4.0.3 on 2022-04-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_remove_enreg_block_file_file_type_delete_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('TOF', 'TOF'), ('TnOF', 'TnOF')], default='TOF', max_length=5),
        ),
    ]
