# Generated by Django 4.0.3 on 2022-04-14 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_file_file_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='nb_max_enregs',
        ),
    ]
