# Generated by Django 4.0.3 on 2022-04-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_remove_file_nb_max_enregs'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_access',
            field=models.CharField(choices=[('sequential', 'sequential'), ('indexed', 'indexed'), ('hashing', 'hashing')], default='sequential', max_length=20),
        ),
    ]
