# Generated by Django 4.0.3 on 2022-04-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_file_file_access_alter_file_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_access',
            field=models.CharField(choices=[('sequential', 'Sequential'), ('indexed', 'Indexed'), ('hashing', 'Hashing')], default='sequential', max_length=30),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('TOF', 'TOF'), ('TnOF', 'TnOF'), ('LOF', 'LOF'), ('LnOF', 'LnOF'), ('clustered', 'Clustered'), ('not_clustered', 'Not Clustered'), ('static', 'Static'), ('dynamic', 'Dynamic')], default='TOF', max_length=30),
        ),
    ]
