# Generated by Django 4.0.3 on 2022-04-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_alter_file_file_access_alter_file_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
