# Generated by Django 4.0.4 on 2022-05-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_file_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('TOF', 'TOF'), ('TnOF', 'TnOF'), ('LOF', 'LOF'), ('LnOF', 'LnOF'), ('clustered', 'Clustered'), ('not_clustered', 'Not Clustered'), ('essai_linear', 'essai_linear')], default='TOF', max_length=30),
        ),
    ]
