# Generated by Django 4.0.4 on 2022-05-15 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_file_show_tutorial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='show_tutorial',
        ),
    ]
